# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

allDescCPP <- function(orig, nTips) {
    .Call('phangorn_allDescCPP', PACKAGE = 'phangorn', orig, nTips)
}

bipartCPP <- function(orig, nTips) {
    .Call('phangorn_bipartCPP', PACKAGE = 'phangorn', orig, nTips)
}

bipCPP <- function(orig, nTips) {
    .Call('phangorn_bipCPP', PACKAGE = 'phangorn', orig, nTips)
}

allChildrenCPP <- function(orig) {
    .Call('phangorn_allChildrenCPP', PACKAGE = 'phangorn', orig)
}

