# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

threshStateC <- function(x, thresholds) {
    .Call(`_phangorn_threshStateC`, x, thresholds)
}

allDescCPP <- function(orig, nTips) {
    .Call(`_phangorn_allDescCPP`, orig, nTips)
}

bipartCPP <- function(orig, nTips) {
    .Call(`_phangorn_bipartCPP`, orig, nTips)
}

bipCPP <- function(orig, nTips) {
    .Call(`_phangorn_bipCPP`, orig, nTips)
}

allChildrenCPP <- function(orig) {
    .Call(`_phangorn_allChildrenCPP`, orig)
}

p2dna <- function(xx, eps = 0.999) {
    .Call(`_phangorn_p2dna`, xx, eps)
}

